force-app/main/default/objects/Client__c/Client__c.object-meta.xml
<CustomObject>
    <label>Client</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Clients</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Client__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Kochi</fullName>
            </value>
            <value>
                <fullName>Trivandrum</fullName>
            </value>
            <value>
                <fullName>Ahemdabad</fullName>
            </value>
            <value>
                <fullName>Surat</fullName>
            </value>
            <value>
                <fullName>Los Angelus</fullName>
            </value>
            <value>
                <fullName>San Fransisco</fullName>
            </value>
            <value>
                <fullName>Miami</fullName>
            </value>
            <value>
                <fullName>Orlando</fullName>
            </value>
            <value>
                <fullName>New York City</fullName>
            </value>
            <value>
                <fullName>Buffalo</fullName>
            </value>
            <value>
                <fullName>Sydney</fullName>
            </value>
            <value>
                <fullName>Newcastle</fullName>
            </value>
            <value>
                <fullName>Adelaide</fullName>
            </value>
            <value>
                <fullName>Port Lincoln</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Manager__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager__c</fullName>
    <inlineHelpText>Name of Employee from Client-Side</inlineHelpText>
    <label>Client Manager</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Client_Manager_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager_Email_ID__c</fullName>
    <label>Client Manager Email ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Company_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Company_Email_ID__c</fullName>
    <label>Company Email ID</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Client__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>USA</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <label>Industry</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agriculture</fullName>
            </value>
            <value>
                <fullName>Basic Metal Production</fullName>
            </value>
            <value>
                <fullName>Chemical industries</fullName>
            </value>
            <value>
                <fullName>Commerce</fullName>
            </value>
            <value>
                <fullName>Construction</fullName>
            </value>
            <value>
                <fullName>Education</fullName>
            </value>
            <value>
                <fullName>Financial services</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Gas</fullName>
            </value>
            <value>
                <fullName>IT</fullName>
            </value>
            <value>
                <fullName>Public Service</fullName>
            </value>
            <value>
                <fullName>Textile</fullName>
            </value>
            <value>
                <fullName>Transport</fullName>
            </value>
            <value>
                <fullName>Utilities</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Client__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>Kerla</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>New York</fullName>
            </value>
            <value>
                <fullName>New South Wales</fullName>
            </value>
            <value>
                <fullName>South Australia</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Project__c/fields/Client__c.field-meta.xml
<CustomField>
    <fullName>Client__c</fullName>
    <label>Client</label>
    <referenceTo>Client__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Client_Manager_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager_Email_ID__c</fullName>
    <formula>Client__r.Client_Manager_Email_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Manager Email ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Description__c.field-meta.xml
<CustomField>
    <fullName>Project_Description__c</fullName>
    <label>Project Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Project_Manager__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager__c</fullName>
    <label>Project Manager</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inprogress</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
            <value>
                <fullName>Planning</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Requirement__c/Requirement__c.object-meta.xml
<CustomObject>
    <label>Requirement</label>
    <nameField>
        <label>Requirement  Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Requirement__c/fields/Client_Manager_Email_ID__c.field-meta.xml
<CustomField>
    <fullName>Client_Manager_Email_ID__c</fullName>
    <formula>Project__r.Client_Manager_Email_ID__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Client Manager Email ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Requirements</relationshipLabel>
    <relationshipName>Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Project_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Project_Manager_Email__c</fullName>
    <formula>Project__r.Project_Manager_Email__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Project Manager Email</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Requirement__c.field-meta.xml
<CustomField>
    <fullName>Requirement__c</fullName>
    <label>Requirement</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Requirement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recall</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NotDeleteReqTest.cls
@isTest
public class NotDeleteReqTest
{ // this test class for do not allow to delete Approved Requirements
    @isTest
    public static void notDeleteTestMethod()
    {
        // Test Client Data
        Client__c cliTest = new CLient__c(Name='TestCLient', Country__c='India', State__c='Maharashtra', 
                                          City__c='Pune', Client_Manager__c='TestClientManager',
                                          Client_Manager_Email_ID__c='testClient_Manager_Email_ID__c@gmail.com',
                            				Company_Email_ID__c='testCompany_Email_ID__c@gmail.com', Industry__c='IT');
        //inserting client data
        insert cliTest;
        system.debug('Client added');
        
        //Test Project Data
        Project__c projectTest = new Project__c(Name='TestProject', Start_Date__c = Date.parse('1/5/2021') , 
                                                End_Date__c =Date.parse('10/5/2021'), Actual_Start_Date__c = Date.parse('2/5/2021') ,
                                               Project_Description__c ='This is Test Project',Budget__c =10000,
                                                Status__c ='Inprogress', Client__c = cliTest.Id, Project_Manager__c='Test Manager',
                                                Project_Manager_Email__c='testProject_Manager_Email__c@gmail.com');
        //Inserting project data
         insert projectTest;
        system.debug('Project added');
        
        //Test Req data
        Requirement__c req = new Requirement__c(Name='TestRequiremnet', Status__c='Approved',
                                                Requirement__c='Test Developer Needed', Project__c =projectTest.Id);
        
        //inserting  Req data
        insert req;
        system.debug('Requ added');
        
        
        // Delete Approved 
        try
        {
            delete req;
        }
        catch(Exception e)
        {
             System.assert(e.getMessage().contains('You can\'t delete this Approved Requirement record !'));
        }
    }
	
}